// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdfyVD79KLL0F1UP8lRCfXm5vEKcn5K_I',
    appId: '1:399061373796:web:ed2bb59bcf793538156071',
    messagingSenderId: '399061373796',
    projectId: 'medlink-2d973',
    authDomain: 'medlink-2d973.firebaseapp.com',
    storageBucket: 'medlink-2d973.firebasestorage.app',
    measurementId: 'G-0EDKH6QTQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAb9hvwNJMv1AgGU8fYBHNfGWeADNn3Kw',
    appId: '1:399061373796:android:f32ebc2225d032b4156071',
    messagingSenderId: '399061373796',
    projectId: 'medlink-2d973',
    storageBucket: 'medlink-2d973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCezvylXO_JYuv2Tl5NJD8zi8TqhYyAYnQ',
    appId: '1:399061373796:ios:f08d957f2453553b156071',
    messagingSenderId: '399061373796',
    projectId: 'medlink-2d973',
    storageBucket: 'medlink-2d973.firebasestorage.app',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCezvylXO_JYuv2Tl5NJD8zi8TqhYyAYnQ',
    appId: '1:399061373796:ios:f08d957f2453553b156071',
    messagingSenderId: '399061373796',
    projectId: 'medlink-2d973',
    storageBucket: 'medlink-2d973.firebasestorage.app',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdfyVD79KLL0F1UP8lRCfXm5vEKcn5K_I',
    appId: '1:399061373796:web:190e03f73f5b5cb0156071',
    messagingSenderId: '399061373796',
    projectId: 'medlink-2d973',
    authDomain: 'medlink-2d973.firebaseapp.com',
    storageBucket: 'medlink-2d973.firebasestorage.app',
    measurementId: 'G-V6X5S9GEHK',
  );
}
